### ISSUE TITLE
Mandala deployment issue

### ISSUE THREAD

**Issue by Yanda1** [Yanda1/protocol#13]
### Problem
Applied [this workaround](https://github.com/Yanda1/acala-test/pull/1) to the current project and still experiencing "evm.OutOfStorage" error.

### How to replicate an error
Start node and rpc adapter locally:
`docker run -it --rm -p 9944:9944 -p 9933:9933 ghcr.io/acalanetwork/mandala-node:sha-189103e --dev --ws-external --rpc-port=9933 --rpc-external --rpc-cors=all --rpc-methods=unsafe --tmp -levmebug`

`LOCAL_MODE=1 npx @acala-network/eth-rpc-adapter`

Run local deployment script:
`npx hardhat run scripts/local_deploy_ext.js --network mandala`

Deployment execution output:
```
 ------------------------------------------
  ⚡️ running in production (standard) mode ⚡️
  ------------------------------------------

ProviderError: Error: evm.OutOfStorage: Storage usage exceeds storage limit
    at HttpProvider.request (/Users/daniel.erstn/Code/Work/Yanda/Protocol/node_modules/hardhat/src/internal/core/providers/http.ts:74:19)
    at HDWalletProvider.request (/Users/daniel.erstn/Code/Work/Yanda/Protocol/node_modules/hardhat/src/internal/core/providers/accounts.ts:182:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EthersProviderWrapper.send (/Users/daniel.erstn/Code/Work/Yanda/Protocol/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

**Comment by ThunderDeliverer** [comment]
I just ran the deploy.js script on the local network and encountered no issues:

```
 yarn hardhat run scripts/deploy.js --network mandala
yarn run v1.22.19
warning package.json: License should be a valid SPDX license expression
$ /Users/jan/Acala/experimental/protocol/node_modules/.bin/hardhat run scripts/deploy.js --network mandala

  ------------------------------------------
  ⚡️ running in production (standard) mode ⚡️
  ------------------------------------------

2022-06-08 12:06:07        API/INIT: RPC methods not decorated: evm_blockLimits
Token deployed
Protocol deployed
Governor deployed
YandaToken deployed at: 0xf80A32A835F79D7787E8a8ee5721D0fEaFd78108
YandaProtocol deployed at: 0xa51EE1845C13Cb03FcA998304b00EcC407fc1F92
YandaGovernor deployed at: 0x85B24b3517E3aC7bf72a14516160541A60cFF19d
✨  Done in 7.40s.
```

Is this an issue that only occurs when you try to deploy to Mandala?

**Comment by Yanda1** [comment]
@ThunderDeliverer thank you, it was my bad, maybe the problem was caused by my M1 chip mac because I tried it now on my windows PC and it works 😅

**Comment by ThunderDeliverer** [comment]
> @ThunderDeliverer thank you, it was my bad, maybe the problem was caused by my M1 chip mac because I tried it now on my windows PC and it works 😅

@Yanda1 I'm using rosetta on mine, so this might be the reason I have no issues with running it 🤔
